### ISSUE TITLE
Another GC algorithm?

### ISSUE THREAD

**Issue by Kirtai** [wingo/whippet#3]
Hi, I wondered if you'd seen the paper [Bare Blocks with a Thin Object Table](https://tinlizzie.org/VPRIPapers/m2007005a_barebloc.pdf) which described a compacting GC that was developed as part of Dr Alan Kay's VPRI research.

I thought you may find it useful as an alternative algorithm for whippet.

**Comment by wingo** [comment]
Thanks for the pointer, that was an interesting read!  I think I don't have any plans to go in that direction, but Whippet may be a good base to try experiments in that direction :)
